---
# file: defaults/main.yml

# Java major version 7 or 8
java_major_version: 8
# Java minor version
java_minor_version: 172

# Parent path to install JDK
java_root_path: /opt/java

# Path to download archives with JDK
java_distr_path: /tmp
# True if you want to use oracle web site to download archive
# False if you have already had downloaded tar archive:
# Just put this file in folder under files folder
# Name should be in format jdk-<major_version>u<minor_version>-linux-x<64_or_86>.tar.gz
java_from_oracle: True

# True if you want to clear download files from java_distr_path folder
java_clear_after: False

# Do you want to set up JAVA_HOME global variable in Linux
java_set_home: True
