---
# vars file for install_mongodb

mongodb_version: '3.4'

mongodb_packages: mongodb-org

mongodb_repo_gpgcheck: True

mongodb_repo_baseurl: "https://repo.mongodb.org/yum/redhat/{{ ansible_distribution_major_version }}/mongodb-org/{{ mongodb_version }}/x86_64/"
mongodb_repo_gpgkey:  "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"

mongodb_packages_dependencies:
  - libselinux-python
